[build]
  publish = "dist"


# React Router rewrite rule (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers + CSP
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "same-origin"
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "fullscreen=(self), camera=(), geolocation=(), microphone=()"
    Vary = "Accept-Language"
    Content-Security-Policy = """
  default-src 'self';
  script-src 'self' https://static.cloudflareinsights.com;;
  style-src 'self' 'unsafe-inline';
  font-src 'self' data:;
  img-src 'self' data: https:;
  connect-src 'self' https://cdn.jsdelivr.net;
  media-src 'self' https://cdn.jsdelivr.net;
  object-src 'none';
  base-uri 'self';
  form-action 'self';
  frame-ancestors 'none';
  upgrade-insecure-requests;
"""




